; core.PL
;
; Alternative polish translation by Misiur
;
; Please look at: http://y-less.pastebin.co.uk
; and: svn://dev.sa-mp.com/sampdev/scripting/YSI

[ysi_properties]

YSI_PROP_NAME = {>GREEN}Nieruchomoœæ: "%s" Cena: $%d Wynagrodzenie: $%d{RED}
YSI_PROP_BUY_HOUSE = Wpisz "/%n" aby nabyæ tê nieruchomoœæ za $%d
YSI_PROP_BUY = Wpisz "/%n" aby kupiæ
YSI_PROP_OWN = Ta nieruchomoœæ jest ju¿ twoja
YSI_PROP_YOURS = Ta nieruchomoœæ jest twoja
YSI_PROP_OUT = {>X11_ALICE_BLUE}"%s" zosta³ kupiony przez %s {SALMON}(%d)
YSI_PROP_OWNER = {>RED}Ta nieruchomoœæ nale¿y do %s (%d){YELLOW}
YSI_PROP_BOUGHT = Naby³eœ "%s" za $%d
YSI_PROP_BOUGHT_HOUSE = {>GREEN}Kupi³eœ ten dom za $%d{RED}
YSI_PROP_HOUSE_OWNED = Ten dom nale¿y do %s
YSI_PROP_NOT = Nie jesteœ w prawid³owej nieruchomoœci
YSI_PROP_CP = Nie jesteœ w checkpoint'cie nieruchomoœci
YSI_PROP_AFFORD = Nie staæ ciê na tê nieruchomoœæ
YSI_PROP_EARNT = Zarobi³eœ $%d na swoich nieruchomoœciach
YSI_PROP_SELL = Wpisz "/%n %d" aby sprzedaæ tê nieruchomoœæ
YSI_PROP_ANN = ~r~%s naby³ %s
YSI_PROP_MAX = Nie mo¿esz kupiæ wiêcej nieruchomoœci.
YSI_PROP_MAX_HOUSE = Nie mo¿esz kupiæ wiêcej domów.
YSI_PROP_ENTER = Wpisz "/%n" ¿eby wejœæ, a "/%n" ¿eby wyjœæ.
; Mo¿esz opuœciæ parametry, ale w kolejnoœci od koñca
; YSI_PROP_SELL = Wpisz "/%n %d" ¿eby sprzedaæ tê nieruchomoœæ za $%d

YSI_BUY_HELP@1 = Pozwala ci kupiæ nieruchomoœæ - te generuj¹
YSI_BUY_HELP@2 = przychód z biegiem czasu i mog¹ byæ bardzo dochodowe.
YSI_BUY_HELP@3 = Musisz byæ w prawid³owej nieruchomoœci ¿eby u¿yæ tej komendy
YSI_BUY_HELP@4 = i zostaniesz poinformowany jeœli w przeciwnym razie

YSI_ENTER_HELP@1 = Pozwala ci wejœæ do jednego z twoich domów
; Napisa³bym "na dworze", ale tyle hejtu w internetach
; o to by³o, ¿e wolê zostawiæ "na zewn¹trz"
YSI_ENTER_HELP@2 = Wpisz to na zewn¹trz ¿eby wejœæ
YSI_ENTER_NOT_YOURS = Nie mo¿esz wchodziæ do cudzych domów
YSI_ENTER_NO_HOUSE = Nie ma tutaj domu do którego mo¿esz wejœæ

YSI_EXIT_HELP@1 = Pozwala ci opuœciæ swój bie¿¹cy dom
YSI_EXIT_NOT_IN = Nie jesteœ w domu
YSI_EXIT_NEAR = Musisz staæ w pobli¿u drzwi ¿eby wyjœæ

YSI_SELL_HELP@1 = Sprzedaje twoj¹ nieruchomoœæ. Mo¿e j¹ sprzedaæ
YSI_SELL_HELP@2 = za ni¿sz¹ kwotê ni¿ ta któr¹ zap³aci³eœ przy kupnie.
YSI_SELL_HELP@3 = Musisz podaæ identyfikator nieruchomoœci któr¹ posiadasz
YSI_SELL_HELP@4 = ale nie musisz byæ w niej
YSI_SELL_NO_ID = Musisz podaæ prawid³owy identyfikator nieruchomoœci
YSI_SELL_CANT = Nie mo¿esz sprzedaæ tej nieruchomoœci
YSI_SELL_OWNER = To nie jest twoja nieruchomoœæ
YSI_SELL_SOLD = Nieruchomoœæ sprzedana za $%d

YSI_FORBIDDEN = Wkraczasz na zastrze¿ony teren
YSI_FORBIDDEN@2 = Uwaga, wkraczasz na %s

YSI_LIST_MULTI = "%s": %d w³aœcicieli
YSI_LIST_FORM = "%s": w³aœciciel "%s"
YSI_LIST_PAGES = U¿yj "/%n <strona>" gdzie <strona> jest z zakresu 1 - %d ¿eby wyœwietliæ listê
YSI_LIST_MORE = Znaleziono wiêcej ni¿ 8 nieruchomoœci

YSI_BANK_NAME = Witaj w banku %s
YSI_BANK_WELCOME = Witaj w banku
YSI_BANK_HELP_1 = Wpisz "/%n <iloœæ>" ¿eby wp³aciæ pieni¹dze
YSI_BANK_HELP_2 = Wpisz "/%n <iloœæ>" ¿eby wyp³aciæ pieni¹dze
YSI_BANK_HELP_3 = Wpisz "/%n" kiedy chcesz ¿eby sprawdziæ saldo
YSI_BANK_BALANCE = Twoje saldo wynosi $%d
YSI_BANK_NOT = Nie jesteœ w banku
YSI_BANK_CP = Musisz staæ w checkpoint'cie banku
YSI_BANK_HELP@1 = Pozwala ci zdeponowaæ pieni¹dze na twoim koncie
YSI_BANK_HELP@2 = Musisz mieæ wystarczaj¹ce œrodki ¿eby zdeponowaæ
YSI_BANK_HELP@3 = podan¹ kwot¹, oraz musisz byæ w banku
YSI_BANK_HELP@4 = U¿ycie: "/%n <kwota>"
YSI_BANK_BANKED = $%d zdeponowane, bie¿¹ce saldo $%d
YSI_BANK_INSUFFICIENT = Niewystarczaj¹ce œrodki do wykonania transakcji

YSI_BAL_HELP = Wyœwietla twoje bie¿¹ce saldo

YSI_WITH_HELP_1 = Pozwala ci wyp³aciæ pieni¹dze z twojego konta
YSI_WITH_HELP_2 = Musisz mieæ wystarczaj¹ce œrodki ¿eby wyp³aciæ
YSI_WITH_HELP_3 = podan¹ kwotê, oraz musisz byæ w banku
YSI_WITH_HELP_4 = U¿ycie: "/%n <kwota>"
YSI_WITHDREW = $%d wyp³acono, bie¿¹ce saldo $%d

YSI_TELS_NAME = Teleportowano do %s
YSI_TELS_TELE = Teleportowano
YSI_TELS_MONEY = Niewystarczaj¹ce œrodki, potrzebujesz $%d ¿eby siê teleportowaæ

YSI_AMMU_NO_MONEY = Nie staæ ciê na tê broñ

YSI_LIST_HELP@1 = Wyœwietla wykaz nieruchomoœci i ich w³aœcicieli
YSI_LIST_HELP@2 = Jeœli jest wiêcej ni¿ 8 nieruchomoœci, zostaj¹ one
YSI_LIST_HELP@3 = podzielone na strony
YSI_LIST_NONE = Nie znaleziono nieruchomoœci

[ysi_race]

YSI_RACE_COUNTDOWN = %d
YSI_RACE_GO = GO GO GO!!!

[ysi_text]

YSI_TEXT_NOT_FOUND = Nie znaleziono ci¹gu "%s" 

[ysi_commands]

YSI_COMM_BLEVEL = Nie mo¿esz u¿yæ tej komendy
YSI_COMM_LIST = "/%s"
YSI_COMM_PAGES = U¿yj "/%n <strona>" gdzie <strona> jest z zakresu 1 - %d ¿eby wyœwietliæ listê
YSI_COMM_MORE = Znaleziono wiêcej ni¿ 8 komand

YSI_COMM_HELP@1 = Wyœwietla listê komend dla skrpytu\n
YSI_COMM_HELP@2 = Jeœli jest wiêcej ni¿ 8 komend, zostaj¹ one podzielone na strony\n
YSI_COMM_HELP@3 = Komendy s¹ wyœwietlone z prefiksami i alternatywnymi nazwami

[ysi_langs]

YSI_LANGS_HELP@1 = Bez parametrów wyœwietla listê jêzyków
YSI_LANGS_HELP@2 = Z parametrem ustawia twój jêzyk na podany
YSI_LANGS_DISP = Jêzyk %d: %s (%s)
YSI_LANGS_MORE = Wpisz "/%n" ¿eby znowu wyœwietliæ wiêcej jêzyków
YSI_LANGS_SET = Wpisz "/%n <id>" ¿eby wybraæ jêzyk
YSI_LANGS_DONE = Jêzyk ustawiony na %d (%s)
YSI_LANGS_INV = Niepoprawny jêzyk

[ysi_help]

YSI_HELP_HELP@1 = Wyœwietla pomoc na temat skryptu lub komendy.
YSI_HELP_HELP@2 = Wpisz "/%n" ¿eby wyœwietliæ pomoc dla skryptu, "/%n <komenda>"
YSI_HELP_HELP@3 = dla pomocy komendy lub "/%n" dla listy komend
YSI_HELP_NOTF = Nieznana funkcja, brak dostêpnej pomocy.

YSI_HELP@1 = <Tutaj nazwa twojego skryptu>\n
YSI_HELP@2 = autorstwa <tutaj twoje imie>,\n
YSI_HELP@3 = w oparciu o YSI autorstwa Alex "Y_Less" Cole'a. \n
YSI_HELP@4 = Dostosuj ten tekst do swoich potrzeb w pliku core.PL\n
YSI_HELP@5 = znajduj¹cym siê w folderze scriptfiles/YSI (domyœlnie).

;YSI_HELP@6 = Zostaw te linijki w spokoju jeœli nie potrzebujesz 10 linijek pomocy i zostan¹ zignorowane.
;YSI_HELP@7 = ; Linijki poprzedzone œrednikiem (;) s¹ komentarzami i nie zostan¹ wyœwietlone
;YSI_HELP@8 = 

; To jest jedyna linia pomocy która mo¿e zawieraæ dane z %n dla komend
;YSI_HELP@9 = Wpisz: "/%n" w celu wyœwietlenia komend i "/%n <komenda>"
;YSI_HELP@10 = ¿eby wyœwietliæ pomoc dla specyficznej komendy (w³¹czaj¹c tê)

[ysi_players]

YSI_LOGIN_HELP@1 = Pozwala ci zalogowaæ siê na konto u¿ywaj¹c has³a które poda³eœ przy rejestracji.

YSI_REGISTER_HELP@1 = Pozwala ci zarejestrowaæ siê na serzerze. Poprosi ciê o podanie has³a i potwierdzenie go.

YSI_GROUP_HELP@1 = Pozwala ci na dodanie bie¿¹cego nicku do innej grupy
YSI_GROUP_HELP@2 = nicków powoduj¹c ¿e te twa nicki wspó³dziel¹ 
YSI_GROUP_HELP@3 = statystyki.  U¿yj "/%n <nick> <has³o>" gdzie <nick> jest
YSI_GROUP_HELP@4 = istniej¹cym zarejestrowanym nickiem a <has³o> jest jego
YSI_GROUP_HELP@5 = has³em ¿eby po³¹czyæ ten nick.

YSI_NSGROUP_PARAMS = U¿ycie: "/%n <zarejestrowany nick> <has³o>"

YSI_REG_TAKEN = Niestety ten nick jest ju¿ zajêty.
YSI_LOGIN_WRONG = Niepoprawne has³o.
YSI_LOGIN_INDERR = B³¹d przy odczycie indeksu, spróbuj ponownie.
YSI_LOGIN_LOGIN = Zalogowany!
YSI_LOGIN_NOTF = Nazwa u¿ytkownika nie znaleziona
YSI_LOGIN_NOLOAD = B³¹d przy otwieraniu pliku u¿ytkownika.
YSI_LOGIN_FAILED = Logowanie odrzucone.
YSI_ADDU_INDER_1 = B³¹d 1 przy dodawaniu pliku gracza.
YSI_ADDU_INDER_2 = B³¹d 2 przy dodawaniu pliku gracza.
YSI_ADDU_SUCC = Poprawnie zarejestrowano.
YSI_LOGIN_ENTER = Musisz podaæ has³o.
YSI_LOGIN_LENGTH = Musisz podaæ has³o maj¹ce przynajmniej 6 znaków.

YSI_LOGIN_ALREADY = Ju¿ jesteœ zalogowany.

YSI_LOGIN_OPTS = Opcje logowania
YSI_LOGIN_OPTIONS_A = Login\r\nZmieñ Nick\r\nZmieñ Jêzyk\r\nWyjdŸ
YSI_LOGIN_OPTIONS_B = Zarejestruj\r\nZmieñ Nick\r\nZmieñ Jêzyk\r\nWyjdŸ

YSI_GROUP_TITLE = Nazwy Grup
YSI_GROUP_NAME = Czy chcia³byœ dodaæ tê nazwê na sta³e?

[ysi_groups]
YSI_CONGRP_HELP@1 = U¿ycie: "/%n <id gracza> <grupa> <dodaj>" OR:
YSI_CONGRP_HELP@2 = "/%n <strona>"
YSI_CONGRP_HELP@3 = Pierwsz¹ opcjê ¿eby przypisaæ gracza do grupy
YSI_CONGRP_HELP@4 = Drug¹ opcjê ¿eby wyœwietliæ listê grup
YSI_CONGRP_HELP@5 = Jeœli dodaj jest równe 1 bêd¹ dodani do podanej
YSI_CONGRP_HELP@6 = grupy, w przeciwnym wypadku zostan¹ usuniêci.
YSI_GROUP_LIST_NAME = Grupa %d: "%s"
YSI_GROUP_LIST_TEMP = Grupa %d: <tymczasowa grupa bez nazwy>
YSI_GROUP_LIST_PAGES = U¿yj "/%n <strona>" gdzie <strona> jest z zakresu 1 - %d ¿eby wyœwietliæ listê
YSI_GROUP_LIST_MORE = Znaleziono wiêcej ni¿ 8 grup
YSI_GROUP_LIST_ASS = Lub "/%n <id gracza> <grupa> <ustaw>" ¿eby przypisaæ grupê
YSI_CONGRP_ASSIGNED = Grupa gracza %d przypisana
YSI_CONGRP_INVALID = Niepoprawne id gracza lub id grupy

[ysi_extras]

YSI_EXTRA_LOGIN_TITLE = Login
YSI_EXTRA_LOGIN_PROMPT = Podaj swoje has³o aby siê zalogowaæ:

YSI_EXTRA_REGISTER_TITLE = Zarejestruj siê
YSI_EXTRA_REGISTER_PROMPT = Proszê podaæ has³o ¿eby siê zarejestrowaæ:
YSI_EXTRA_REGISTER_MISMATCH = Has³a siê nie zgadzaj¹. Spróbuj ponownie.

YSI_EXTRA_CONFIRM_PROMPT = PotwierdŸ swoje has³o:

[ysi_dialog]

DIALOG_ACCEPT = Akceptuj
DIALOG_CANCEL = Anuluj
DIALOG_OK = OK
DIALOG_YES = Tak
DIALOG_NO = Nie
DIALOG_CLOSE = Zamknij
DIALOG_BACK = Wróæ
DIALOG_FORWARD = Nastêpny
DIALOG_PREVIOUS = Poprzedni
DIALOG_NEXT = Nastêpny
DIALOG_EXIT = Wyjœcie
DIALOG_OPTIONS = Opcje
DIALOG_SELECT = Wybierz
DIALOG_ADD = Dodaj
DIALOG_REMOVE = Usuñ
DIALOG_QUIT = WyjdŸ
DIALOG_NONE =

[ysi_zonenames]
YSI_ZONE_NAME = %s%s

