#include <YSI_Coding\y_hooks>

#include "modules/Player/Security.pwn"
#include "modules/Player/Functions.pwn"
// Jobs
#include "modules/Player/Jobs/Garbage.pwn"
#include "modules/Player/Jobs/Sweeper.pwn"
#include "modules/Player/Jobs/Mechanic.pwn"
#include "modules/Player/Jobs/Crafter.pwn"
#include "modules/Player/Jobs/Farmer.pwn"
#include "modules/Player/Jobs/Jacker.pwn"
#include "modules/Player/Jobs/Logger.pwn"
#include "modules/Player/Jobs/Impounder.pwn"
#include "modules/Player/Jobs/Transporter.pwn"
#include "modules/Player/Jobs/Taxi.pwn"
#include "modules/Player/Jobs/Funcs.pwn"

#include "modules/Player/AFKTimer.pwn"
#include "modules/Player/SaveLoad.pwn"
#include "modules/Player/Tutorial.pwn"
#include "modules/Player/RPQuiz.pwn"
#include "modules/Player/PayDay.pwn"
#include "modules/Player/CMD.pwn"
#include "modules/Player/Help.pwn"