#include "modules/Systems/Factions\Core.pwn"

// LSPD
#include "modules/Systems/Factions\LSPD/EVLS.pwn"
#include "modules/Systems/Factions\LSPD/Flare.pwn"
#include "modules/Systems/Factions\LSPD/Wiretap.pwn"
#include "modules/Systems/Factions\LSPD/SWAT.pwn"
#include "modules/Systems/Factions\LSPD/ANPR.pwn"
#include "modules/Systems/Factions\LSPD/Roadblocks.pwn"
#include "modules/Systems/Factions\LSPD/MDC.pwn"
#include "modules/Systems/Factions\LSPD/Flashbang.pwn"
#include "modules/Systems/Factions\LSPD/Tickets.pwn"
#include "modules/Systems/Factions\LSPD/Spikes.pwn"
#include "modules/Systems/Factions\LSPD/Gunrack.pwn"
#include "modules/Systems/Factions\LSPD/MobileCommand.pwn"
#include "modules/Systems/Factions\LSPD/Siren.pwn"
#include "modules/Systems/Factions\LSPD/Core.pwn"

// LSFD
#include "modules/Systems/Factions\LSFD/Ambulance.pwn"
#include "modules/Systems/Factions\LSFD/Anamnesis.pwn"
#include "modules/Systems/Factions\LSFD/Rope.pwn"
#include "modules/Systems/Factions\LSFD/Core.pwn"

// Government
#include "modules/Systems/Factions\Mayor/Elections.pwn"
#include "modules/Systems/Factions\Mayor/Budget.pwn"
#include "modules/Systems/Factions\Mayor/Core.pwn"

// News, Racers & Illegal Warehouses
#include "modules/Systems/Factions\LSN.pwn"
#include "modules/Systems/Factions\Race.pwn"
#include "modules/Systems/Factions\Warehouse.pwn"