// Vehicles
#include "modules/Systems\Vehicles/Core.inc"

// House
#include "modules/Systems\House/Core.inc"

// Bizz
#include "modules/Systems\Bizz/Core.inc"

// Casino
#include "modules/Systems/Casino/Rulet.pwn"
#include "modules/Systems/Casino/Poker.pwn"

// Events
#include "modules/Systems/Events/Core.pwn"
#include "modules/Systems/Events/Dakar.pwn"
#include "modules/Systems/Events/Quad.pwn"

// Misc
#include "modules/Systems/Pickups.pwn"
#include "modules/Systems/Ammunation.pwn"
#include "modules/Systems/Complex.pwn"
#include "modules/Systems/Graffiti.pwn"
#include "modules/Systems/PawnShop.pwn"
#include "modules/Systems/GPS.pwn"

// Factions
#include "modules/Systems\Factions/Core.inc"