// Char folder modules represent non database storing features.

// Hobbies
#include "modules/Char/Hobby/Fisher.pwn"
#include "modules/Char/Hobby/Hunter.pwn"

#include "modules/Char/Animations.pwn"
#include "modules/Char/Hotel.pwn"
#include "modules/Char/Bombs.pwn"
#include "modules/Char/BoomBox.pwn"
#include "modules/Char/Jail.pwn"
#include "modules/Char/DMV.pwn"
#include "modules/Char/ATM.pwn"
#include "modules/Char/Stripper.pwn"
#include "modules/Char/Prostitute.pwn"
#include "modules/Char/Spraynpay.pwn"
#include "modules/Char/Food.pwn"
#include "modules/Char/Ads.pwn"
#include "modules/Char/CreateObjects.pwn"
#include "modules/Char/Travel.pwn"
#include "modules/Char/Toll.pwn"
#include "modules/Char/Speedo.pwn"
#include "modules/Char/Rentveh.pwn"
#include "modules/Char/Basketball.pwn"